#include "../Source/animation.cpp"
#include "../Source/enemy.cpp"
#include "../Source/fight_logic.cpp"
#include "../Source/frame.cpp"
#include "../Source/frame_rect.cpp"
#include "../Source/game.cpp"
#include "../Source/hp_bar.cpp"
#include "../Source/jump.cpp"
#include "../Source/level.cpp"
#include "../Source/logic.cpp"
#include "../Source/movement.cpp"
#include "../Source/player.cpp"
#include "../Source/visual.cpp"
#include "../Source/main.cpp"

#include "../TinyXML/tinystr.cpp"
#include "../TinyXML/tinyxml.cpp"
#include "../TinyXML/tinyxmlerror.cpp"
#include "../TinyXML/tinyxmlparser.cpp"

#include "../Libs/json_spirit/json_spirit_reader.cpp"
#include "../Libs/json_spirit/json_spirit_value.cpp"
#include "../Libs/json_spirit/json_spirit_writer.cpp"
